// Generated by gmmproc 2.46.1 -- DO NOT MODIFY!


#include <glibmm.h>

#include <gtksourceviewmm/completioninfo.h>
#include <gtksourceviewmm/private/completioninfo_p.h>


/* completioninfo.cc
 *
 * Copyright (C) 2009, 2010, 2011 Krzesimir Nowak
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include <gtksourceview/gtksourcecompletioninfo.h>

namespace Gsv
{

CompletionInfo::CompletionInfo() :
  // Mark this class as non-derived to allow C++ vfuncs to be skipped.
  Glib::ObjectBase(0),
  Gtk::Window(Glib::ConstructParams(completioninfo_class_.init(), "type",GTK_WINDOW_POPUP, static_cast<char*>(0)))
{}

void
CompletionInfo::move_to_iter(const Gtk::TextView& view)
{
  gtk_source_completion_info_move_to_iter(gobj(), const_cast<GtkTextView*>(view.gobj()), 0);
}

} // namespace Gsv

namespace
{

#ifndef GTKSOURCEVIEWMM_DISABLE_DEPRECATED


static const Glib::SignalProxyInfo CompletionInfo_signal_before_show_info =
{
  "before-show",
  (GCallback) &Glib::SignalProxyNormal::slot0_void_callback,
  (GCallback) &Glib::SignalProxyNormal::slot0_void_callback
};

#endif // GTKSOURCEVIEWMM_DISABLE_DEPRECATED


} // anonymous namespace


namespace Glib
{

Gsv::CompletionInfo* wrap(GtkSourceCompletionInfo* object, bool take_copy)
{
  return dynamic_cast<Gsv::CompletionInfo *> (Glib::wrap_auto ((GObject*)(object), take_copy));
}

} /* namespace Glib */

namespace Gsv
{


/* The *_Class implementation: */

const Glib::Class& CompletionInfo_Class::init()
{
  if(!gtype_) // create the GType if necessary
  {
    // Glib::Class has to know the class init function to clone custom types.
    class_init_func_ = &CompletionInfo_Class::class_init_function;

    // This is actually just optimized away, apparently with no harm.
    // Make sure that the parent type has been created.
    //CppClassParent::CppObjectType::get_type();

    // Create the wrapper type, with the same class/instance size as the base type.
    register_derived_type(gtk_source_completion_info_get_type());

    // Add derived versions of interfaces, if the C type implements any interfaces:

  }

  return *this;
}


void CompletionInfo_Class::class_init_function(void* g_class, void* class_data)
{
  const auto klass = static_cast<BaseClassType*>(g_class);
  CppClassParent::class_init_function(klass, class_data);


#ifndef GTKSOURCEVIEWMM_DISABLE_DEPRECATED

  klass->before_show = &before_show_callback;
#endif // GTKSOURCEVIEWMM_DISABLE_DEPRECATED

}


#ifndef GTKSOURCEVIEWMM_DISABLE_DEPRECATED

void CompletionInfo_Class::before_show_callback(GtkSourceCompletionInfo* self)
{
  const auto obj_base = static_cast<Glib::ObjectBase*>(
      Glib::ObjectBase::_get_current_wrapper((GObject*)self));

  // Non-gtkmmproc-generated custom classes implicitly call the default
  // Glib::ObjectBase constructor, which sets is_derived_. But gtkmmproc-
  // generated classes can use this optimisation, which avoids the unnecessary
  // parameter conversions if there is no possibility of the virtual function
  // being overridden:
  if(obj_base && obj_base->is_derived_())
  {
    const auto obj = dynamic_cast<CppObjectType* const>(obj_base);
    if(obj) // This can be NULL during destruction.
    {
      try // Trap C++ exceptions which would normally be lost because this is a C callback.
      {
        // Call the virtual member method, which derived classes might override.
        obj->on_before_show();
        return;
      }
      catch(...)
      {
        Glib::exception_handlers_invoke();
      }
    }
  }

  const auto base = static_cast<BaseClassType*>(
        g_type_class_peek_parent(G_OBJECT_GET_CLASS(self)) // Get the parent class of the object class (The original underlying C class).
    );

  // Call the original underlying C function:
  if(base && base->before_show)
    (*base->before_show)(self);
}
#endif // GTKSOURCEVIEWMM_DISABLE_DEPRECATED


Glib::ObjectBase* CompletionInfo_Class::wrap_new(GObject* o)
{
  return manage(new CompletionInfo((GtkSourceCompletionInfo*)(o)));

}


/* The implementation: */

CompletionInfo::CompletionInfo(const Glib::ConstructParams& construct_params)
:
  Gtk::Window(construct_params)
{
  }

CompletionInfo::CompletionInfo(GtkSourceCompletionInfo* castitem)
:
  Gtk::Window((GtkWindow*)(castitem))
{
  }


CompletionInfo::CompletionInfo(CompletionInfo&& src) noexcept
: Gtk::Window(std::move(src))
{}

CompletionInfo& CompletionInfo::operator=(CompletionInfo&& src) noexcept
{
  Gtk::Window::operator=(std::move(src));
  return *this;
}

CompletionInfo::~CompletionInfo() noexcept
{
  destroy_();
}

CompletionInfo::CppClassType CompletionInfo::completioninfo_class_; // initialize static member

GType CompletionInfo::get_type()
{
  return completioninfo_class_.init().get_type();
}


GType CompletionInfo::get_base_type()
{
  return gtk_source_completion_info_get_type();
}


void CompletionInfo::move_to_iter(const Gtk::TextView& view, const Gtk::TextIter& iter)
{
  gtk_source_completion_info_move_to_iter(gobj(), const_cast<GtkTextView*>((view).gobj()), const_cast<GtkTextIter*>((iter).gobj()));
}

#ifndef GTKSOURCEVIEWMM_DISABLE_DEPRECATED
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
void CompletionInfo::set_widget(Gtk::Widget& widget)
{
  gtk_source_completion_info_set_widget(gobj(), (widget).gobj());
}
G_GNUC_END_IGNORE_DEPRECATIONS
#endif // GTKSOURCEVIEWMM_DISABLE_DEPRECATED

#ifndef GTKSOURCEVIEWMM_DISABLE_DEPRECATED
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
Gtk::Widget* CompletionInfo::get_widget()
{
  return Glib::wrap(gtk_source_completion_info_get_widget(gobj()));
}
G_GNUC_END_IGNORE_DEPRECATIONS
#endif // GTKSOURCEVIEWMM_DISABLE_DEPRECATED

#ifndef GTKSOURCEVIEWMM_DISABLE_DEPRECATED
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
const Gtk::Widget* CompletionInfo::get_widget() const
{
  return const_cast<CompletionInfo*>(this)->get_widget();
}
G_GNUC_END_IGNORE_DEPRECATIONS
#endif // GTKSOURCEVIEWMM_DISABLE_DEPRECATED


#ifndef GTKSOURCEVIEWMM_DISABLE_DEPRECATED

Glib::SignalProxy0< void > CompletionInfo::signal_before_show()
{
  return Glib::SignalProxy0< void >(this, &CompletionInfo_signal_before_show_info);
}
#endif // GTKSOURCEVIEWMM_DISABLE_DEPRECATED


void Gsv::CompletionInfo::on_before_show()
{
  const auto base = static_cast<BaseClassType*>(
      g_type_class_peek_parent(G_OBJECT_GET_CLASS(gobject_)) // Get the parent class of the object class (The original underlying C class).
  );

  if(base && base->before_show)
    (*base->before_show)(gobj());
}


} // namespace Gsv


